"""Added country code fields to Tld model

Revision ID: 002ea6028992
Revises: eec01ccb2fcb
Create Date: 2021-12-31 04:34:37.105405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002ea6028992'
down_revision = 'eec01ccb2fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tld', sa.Column('cc', sa.String(), nullable=True))
    op.add_column('tld', sa.Column('type_', sa.String(), nullable=True))
    op.create_index(op.f('ix_tld_cc'), 'tld', ['cc'], unique=False)
    op.create_index(op.f('ix_tld_type_'), 'tld', ['type_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tld_type_'), table_name='tld')
    op.drop_index(op.f('ix_tld_cc'), table_name='tld')
    op.drop_column('tld', 'type_')
    op.drop_column('tld', 'cc')
    # ### end Alembic commands ###
