"""Updated all models

Revision ID: 09512d00b2c0
Revises: eb805b1250ff
Create Date: 2022-02-05 00:38:31.780810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09512d00b2c0'
down_revision = 'eb805b1250ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iana_root_server', sa.Column('country', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('url_home', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('location', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('srv_operator', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('srv_type', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('num_inst', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('srv_contact', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('peer_pol', sa.String(), nullable=True))
    op.add_column('iana_root_server', sa.Column('updated', sa.String(), nullable=True))
    op.drop_index('ix_iana_root_server_con', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_ctry', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_inst', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_loc', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_oper', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_peer', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_type_', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_uni', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_updt', table_name='iana_root_server')
    op.drop_index('ix_iana_root_server_url', table_name='iana_root_server')
    op.create_index(op.f('ix_iana_root_server_country'), 'iana_root_server', ['country'], unique=False)
    op.create_index(op.f('ix_iana_root_server_location'), 'iana_root_server', ['location'], unique=False)
    op.create_index(op.f('ix_iana_root_server_num_inst'), 'iana_root_server', ['num_inst'], unique=False)
    op.create_index(op.f('ix_iana_root_server_peer_pol'), 'iana_root_server', ['peer_pol'], unique=False)
    op.create_index(op.f('ix_iana_root_server_srv_contact'), 'iana_root_server', ['srv_contact'], unique=False)
    op.create_index(op.f('ix_iana_root_server_srv_operator'), 'iana_root_server', ['srv_operator'], unique=False)
    op.create_index(op.f('ix_iana_root_server_srv_type'), 'iana_root_server', ['srv_type'], unique=False)
    op.create_index(op.f('ix_iana_root_server_updated'), 'iana_root_server', ['updated'], unique=False)
    op.create_index(op.f('ix_iana_root_server_url_home'), 'iana_root_server', ['url_home'], unique=False)
    op.drop_column('iana_root_server', 'url')
    op.drop_column('iana_root_server', 'updt')
    op.drop_column('iana_root_server', 'ctry')
    op.drop_column('iana_root_server', 'type_')
    op.drop_column('iana_root_server', 'inst')
    op.drop_column('iana_root_server', 'con')
    op.drop_column('iana_root_server', 'peer')
    op.drop_column('iana_root_server', 'oper')
    op.drop_column('iana_root_server', 'loc')
    op.drop_column('iana_root_server', 'uni')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iana_root_server', sa.Column('uni', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('loc', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('oper', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('peer', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('con', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('inst', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('type_', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('ctry', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('updt', sa.VARCHAR(), nullable=True))
    op.add_column('iana_root_server', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_iana_root_server_url_home'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_updated'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_srv_type'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_srv_operator'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_srv_contact'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_peer_pol'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_num_inst'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_location'), table_name='iana_root_server')
    op.drop_index(op.f('ix_iana_root_server_country'), table_name='iana_root_server')
    op.create_index('ix_iana_root_server_url', 'iana_root_server', ['url'], unique=False)
    op.create_index('ix_iana_root_server_updt', 'iana_root_server', ['updt'], unique=False)
    op.create_index('ix_iana_root_server_uni', 'iana_root_server', ['uni'], unique=False)
    op.create_index('ix_iana_root_server_type_', 'iana_root_server', ['type_'], unique=False)
    op.create_index('ix_iana_root_server_peer', 'iana_root_server', ['peer'], unique=False)
    op.create_index('ix_iana_root_server_oper', 'iana_root_server', ['oper'], unique=False)
    op.create_index('ix_iana_root_server_loc', 'iana_root_server', ['loc'], unique=False)
    op.create_index('ix_iana_root_server_inst', 'iana_root_server', ['inst'], unique=False)
    op.create_index('ix_iana_root_server_ctry', 'iana_root_server', ['ctry'], unique=False)
    op.create_index('ix_iana_root_server_con', 'iana_root_server', ['con'], unique=False)
    op.drop_column('iana_root_server', 'updated')
    op.drop_column('iana_root_server', 'peer_pol')
    op.drop_column('iana_root_server', 'srv_contact')
    op.drop_column('iana_root_server', 'num_inst')
    op.drop_column('iana_root_server', 'srv_type')
    op.drop_column('iana_root_server', 'srv_operator')
    op.drop_column('iana_root_server', 'location')
    op.drop_column('iana_root_server', 'url_home')
    op.drop_column('iana_root_server', 'country')
    # ### end Alembic commands ###
