"""Added min and max density columns to Pop_dens model

Revision ID: 0de913e2c09b
Revises: 2545034333e4
Create Date: 2022-01-01 07:28:01.737186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de913e2c09b'
down_revision = '2545034333e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pop_dens', sa.Column('max_', sa.String(), nullable=True))
    op.add_column('pop_dens', sa.Column('min_', sa.String(), nullable=True))
    op.create_index(op.f('ix_pop_dens_max_'), 'pop_dens', ['max_'], unique=False)
    op.create_index(op.f('ix_pop_dens_min_'), 'pop_dens', ['min_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pop_dens_min_'), table_name='pop_dens')
    op.drop_index(op.f('ix_pop_dens_max_'), table_name='pop_dens')
    op.drop_column('pop_dens', 'min_')
    op.drop_column('pop_dens', 'max_')
    # ### end Alembic commands ###
