"""Updated models for Root Servers

Revision ID: 1ddba62d0e58
Revises: af56d0f3f3f1
Create Date: 2021-12-24 09:08:47.055101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddba62d0e58'
down_revision = 'af56d0f3f3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_srv', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_root_srv_uni'), 'root_srv', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_root_srv_uni'), table_name='root_srv')
    op.drop_column('root_srv', 'uni')
    # ### end Alembic commands ###
