"""Added url to Root_srv model

Revision ID: 2545034333e4
Revises: d87d4d1ec532
Create Date: 2021-12-31 06:30:23.874139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2545034333e4'
down_revision = 'd87d4d1ec532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_srv', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_root_srv_url'), 'root_srv', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_root_srv_url'), table_name='root_srv')
    op.drop_column('root_srv', 'url')
    # ### end Alembic commands ###
