"""Updated Submarine Cable Landing Points model

Revision ID: 2709e836f731
Revises: 4e1a0f12b846
Create Date: 2021-12-25 15:20:50.902158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2709e836f731'
down_revision = '4e1a0f12b846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('reg', sa.String(), nullable=True))
    op.drop_index('ix_land_car', table_name='land')
    op.create_index(op.f('ix_land_reg'), 'land', ['reg'], unique=False)
    op.drop_column('land', 'car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('car', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_land_reg'), table_name='land')
    op.create_index('ix_land_car', 'land', ['car'], unique=False)
    op.drop_column('land', 'reg')
    # ### end Alembic commands ###
