"""Modified GNI, PPP, and USD models

Revision ID: 28d4b7fda907
Revises: 4483cb198a58
Create Date: 2021-12-24 04:07:49.931772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d4b7fda907'
down_revision = '4483cb198a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GNI', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_GNI_uni'), 'GNI', ['uni'], unique=False)
    op.add_column('PPP', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_PPP_uni'), 'PPP', ['uni'], unique=False)
    op.add_column('USD', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_USD_uni'), 'USD', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USD_uni'), table_name='USD')
    op.drop_column('USD', 'uni')
    op.drop_index(op.f('ix_PPP_uni'), table_name='PPP')
    op.drop_column('PPP', 'uni')
    op.drop_index(op.f('ix_GNI_uni'), table_name='GNI')
    op.drop_column('GNI', 'uni')
    # ### end Alembic commands ###
