"""Updated Root Server models

Revision ID: 2e6074b71a9c
Revises: 6bec74d74967
Create Date: 2021-12-26 04:32:27.886376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6074b71a9c'
down_revision = '6bec74d74967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_srv', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('root_srv', sa.Column('lon', sa.Float(), nullable=True))
    op.create_index(op.f('ix_root_srv_lat'), 'root_srv', ['lat'], unique=False)
    op.create_index(op.f('ix_root_srv_lon'), 'root_srv', ['lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_root_srv_lon'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_lat'), table_name='root_srv')
    op.drop_column('root_srv', 'lon')
    op.drop_column('root_srv', 'lat')
    # ### end Alembic commands ###
