"""Updated Population Density model

Revision ID: 385f20cc0509
Revises: 76092dcf08c1
Create Date: 2021-12-26 06:32:41.080589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385f20cc0509'
down_revision = '76092dcf08c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pop_dens', sa.Column('dens', sa.String(), nullable=True))
    op.create_index(op.f('ix_pop_dens_dens'), 'pop_dens', ['dens'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pop_dens_dens'), table_name='pop_dens')
    op.drop_column('pop_dens', 'dens')
    # ### end Alembic commands ###
