"""Added timestamp fields in models

Revision ID: 4483cb198a58
Revises: ff0f8fa69600
Create Date: 2021-12-24 02:38:49.981682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4483cb198a58'
down_revision = 'ff0f8fa69600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ixp_dir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('prfs', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lon', sa.String(), nullable=True),
    sa.Column('prts', sa.String(), nullable=True),
    sa.Column('ipv4_avg', sa.String(), nullable=True),
    sa.Column('ipv4_pk', sa.String(), nullable=True),
    sa.Column('ipv6_avg', sa.String(), nullable=True),
    sa.Column('updt', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ixp_dir_city'), 'ixp_dir', ['city'], unique=False)
    op.create_index(op.f('ix_ixp_dir_ctry'), 'ixp_dir', ['ctry'], unique=False)
    op.create_index(op.f('ix_ixp_dir_date'), 'ixp_dir', ['date'], unique=False)
    op.create_index(op.f('ix_ixp_dir_ipv4_avg'), 'ixp_dir', ['ipv4_avg'], unique=False)
    op.create_index(op.f('ix_ixp_dir_ipv4_pk'), 'ixp_dir', ['ipv4_pk'], unique=False)
    op.create_index(op.f('ix_ixp_dir_ipv6_avg'), 'ixp_dir', ['ipv6_avg'], unique=False)
    op.create_index(op.f('ix_ixp_dir_lat'), 'ixp_dir', ['lat'], unique=False)
    op.create_index(op.f('ix_ixp_dir_lon'), 'ixp_dir', ['lon'], unique=False)
    op.create_index(op.f('ix_ixp_dir_name'), 'ixp_dir', ['name'], unique=False)
    op.create_index(op.f('ix_ixp_dir_prfs'), 'ixp_dir', ['prfs'], unique=False)
    op.create_index(op.f('ix_ixp_dir_prts'), 'ixp_dir', ['prts'], unique=False)
    op.create_index(op.f('ix_ixp_dir_stamp'), 'ixp_dir', ['stamp'], unique=False)
    op.create_index(op.f('ix_ixp_dir_stat'), 'ixp_dir', ['stat'], unique=False)
    op.create_index(op.f('ix_ixp_dir_updt'), 'ixp_dir', ['updt'], unique=False)
    op.create_index(op.f('ix_ixp_dir_url'), 'ixp_dir', ['url'], unique=False)
    op.create_table('ixp_mem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('fqdn', sa.String(), nullable=True),
    sa.Column('ping', sa.String(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('peer', sa.String(), nullable=True),
    sa.Column('prfs', sa.String(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ixp_mem_asn'), 'ixp_mem', ['asn'], unique=False)
    op.create_index(op.f('ix_ixp_mem_ctry'), 'ixp_mem', ['ctry'], unique=False)
    op.create_index(op.f('ix_ixp_mem_fqdn'), 'ixp_mem', ['fqdn'], unique=False)
    op.create_index(op.f('ix_ixp_mem_ip'), 'ixp_mem', ['ip'], unique=False)
    op.create_index(op.f('ix_ixp_mem_ipv4'), 'ixp_mem', ['ipv4'], unique=False)
    op.create_index(op.f('ix_ixp_mem_ipv6'), 'ixp_mem', ['ipv6'], unique=False)
    op.create_index(op.f('ix_ixp_mem_org'), 'ixp_mem', ['org'], unique=False)
    op.create_index(op.f('ix_ixp_mem_peer'), 'ixp_mem', ['peer'], unique=False)
    op.create_index(op.f('ix_ixp_mem_ping'), 'ixp_mem', ['ping'], unique=False)
    op.create_index(op.f('ix_ixp_mem_prfs'), 'ixp_mem', ['prfs'], unique=False)
    op.create_index(op.f('ix_ixp_mem_stamp'), 'ixp_mem', ['stamp'], unique=False)
    op.create_table('ixp_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ver', sa.String(), nullable=True),
    sa.Column('sub', sa.String(), nullable=True),
    sa.Column('mlpa', sa.String(), nullable=True),
    sa.Column('traf', sa.String(), nullable=True),
    sa.Column('prts', sa.String(), nullable=True),
    sa.Column('est', sa.String(), nullable=True),
    sa.Column('url_traf', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ixp_sub_ctry'), 'ixp_sub', ['ctry'], unique=False)
    op.create_index(op.f('ix_ixp_sub_est'), 'ixp_sub', ['est'], unique=False)
    op.create_index(op.f('ix_ixp_sub_mlpa'), 'ixp_sub', ['mlpa'], unique=False)
    op.create_index(op.f('ix_ixp_sub_name'), 'ixp_sub', ['name'], unique=False)
    op.create_index(op.f('ix_ixp_sub_prts'), 'ixp_sub', ['prts'], unique=False)
    op.create_index(op.f('ix_ixp_sub_stamp'), 'ixp_sub', ['stamp'], unique=False)
    op.create_index(op.f('ix_ixp_sub_stat'), 'ixp_sub', ['stat'], unique=False)
    op.create_index(op.f('ix_ixp_sub_sub'), 'ixp_sub', ['sub'], unique=False)
    op.create_index(op.f('ix_ixp_sub_traf'), 'ixp_sub', ['traf'], unique=False)
    op.create_index(op.f('ix_ixp_sub_url_traf'), 'ixp_sub', ['url_traf'], unique=False)
    op.create_index(op.f('ix_ixp_sub_ver'), 'ixp_sub', ['ver'], unique=False)
    op.create_table('land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('car', sa.String(), nullable=True),
    sa.Column('updt', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_car'), 'land', ['car'], unique=False)
    op.create_index(op.f('ix_land_ctry'), 'land', ['ctry'], unique=False)
    op.create_index(op.f('ix_land_lat'), 'land', ['lat'], unique=False)
    op.create_index(op.f('ix_land_lon'), 'land', ['lon'], unique=False)
    op.create_index(op.f('ix_land_name'), 'land', ['name'], unique=False)
    op.create_index(op.f('ix_land_stamp'), 'land', ['stamp'], unique=False)
    op.create_index(op.f('ix_land_updt'), 'land', ['updt'], unique=False)
    op.drop_index('ix_src_updt_src', table_name='src_updt')
    op.drop_index('ix_src_updt_updt', table_name='src_updt')
    op.drop_table('src_updt')
    op.drop_index('ix_car_land_ctry', table_name='car_land')
    op.drop_index('ix_car_land_lat', table_name='car_land')
    op.drop_index('ix_car_land_lon', table_name='car_land')
    op.drop_index('ix_car_land_name', table_name='car_land')
    op.drop_table('car_land')
    op.drop_index('ix_int_land_ctry', table_name='int_land')
    op.drop_index('ix_int_land_lat', table_name='int_land')
    op.drop_index('ix_int_land_lon', table_name='int_land')
    op.drop_index('ix_int_land_name', table_name='int_land')
    op.drop_table('int_land')
    op.add_column('GNI', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('GNI', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_GNI_stamp'), 'GNI', ['stamp'], unique=False)
    op.create_index(op.f('ix_GNI_updt'), 'GNI', ['updt'], unique=False)
    op.add_column('ICT_bw', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('ICT_bw', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_ICT_bw_stamp'), 'ICT_bw', ['stamp'], unique=False)
    op.create_index(op.f('ix_ICT_bw_updt'), 'ICT_bw', ['updt'], unique=False)
    op.add_column('ICT_fix', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('ICT_fix', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_ICT_fix_stamp'), 'ICT_fix', ['stamp'], unique=False)
    op.create_index(op.f('ix_ICT_fix_updt'), 'ICT_fix', ['updt'], unique=False)
    op.add_column('ICT_mob', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('ICT_mob', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_ICT_mob_stamp'), 'ICT_mob', ['stamp'], unique=False)
    op.create_index(op.f('ix_ICT_mob_updt'), 'ICT_mob', ['updt'], unique=False)
    op.add_column('ICT_per', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('ICT_per', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_ICT_per_stamp'), 'ICT_per', ['stamp'], unique=False)
    op.create_index(op.f('ix_ICT_per_updt'), 'ICT_per', ['updt'], unique=False)
    op.add_column('PPP', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('PPP', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_PPP_stamp'), 'PPP', ['stamp'], unique=False)
    op.create_index(op.f('ix_PPP_updt'), 'PPP', ['updt'], unique=False)
    op.add_column('USD', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('USD', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_USD_stamp'), 'USD', ['stamp'], unique=False)
    op.create_index(op.f('ix_USD_updt'), 'USD', ['updt'], unique=False)
    op.add_column('fixed_br', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_fixed_br_stamp'), 'fixed_br', ['stamp'], unique=False)
    op.add_column('gen_pop', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_gen_pop_stamp'), 'gen_pop', ['stamp'], unique=False)
    op.add_column('mob_br', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_mob_br_stamp'), 'mob_br', ['stamp'], unique=False)
    op.add_column('pop_dens', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_pop_dens_stamp'), 'pop_dens', ['stamp'], unique=False)
    op.add_column('root_srv', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('root_srv', sa.Column('stamp', sa.String(), nullable=True))
    op.drop_index('ix_root_srv_sub', table_name='root_srv')
    op.create_index(op.f('ix_root_srv_stamp'), 'root_srv', ['stamp'], unique=False)
    op.create_index(op.f('ix_root_srv_updt'), 'root_srv', ['updt'], unique=False)
    op.drop_column('root_srv', 'sub')
    op.add_column('tld', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_tld_stamp'), 'tld', ['stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tld_stamp'), table_name='tld')
    op.drop_column('tld', 'stamp')
    op.add_column('root_srv', sa.Column('sub', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_root_srv_updt'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_stamp'), table_name='root_srv')
    op.create_index('ix_root_srv_sub', 'root_srv', ['sub'], unique=False)
    op.drop_column('root_srv', 'stamp')
    op.drop_column('root_srv', 'updt')
    op.drop_index(op.f('ix_pop_dens_stamp'), table_name='pop_dens')
    op.drop_column('pop_dens', 'stamp')
    op.drop_index(op.f('ix_mob_br_stamp'), table_name='mob_br')
    op.drop_column('mob_br', 'stamp')
    op.drop_index(op.f('ix_gen_pop_stamp'), table_name='gen_pop')
    op.drop_column('gen_pop', 'stamp')
    op.drop_index(op.f('ix_fixed_br_stamp'), table_name='fixed_br')
    op.drop_column('fixed_br', 'stamp')
    op.drop_index(op.f('ix_USD_updt'), table_name='USD')
    op.drop_index(op.f('ix_USD_stamp'), table_name='USD')
    op.drop_column('USD', 'stamp')
    op.drop_column('USD', 'updt')
    op.drop_index(op.f('ix_PPP_updt'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_stamp'), table_name='PPP')
    op.drop_column('PPP', 'stamp')
    op.drop_column('PPP', 'updt')
    op.drop_index(op.f('ix_ICT_per_updt'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_stamp'), table_name='ICT_per')
    op.drop_column('ICT_per', 'stamp')
    op.drop_column('ICT_per', 'updt')
    op.drop_index(op.f('ix_ICT_mob_updt'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_stamp'), table_name='ICT_mob')
    op.drop_column('ICT_mob', 'stamp')
    op.drop_column('ICT_mob', 'updt')
    op.drop_index(op.f('ix_ICT_fix_updt'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_stamp'), table_name='ICT_fix')
    op.drop_column('ICT_fix', 'stamp')
    op.drop_column('ICT_fix', 'updt')
    op.drop_index(op.f('ix_ICT_bw_updt'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_stamp'), table_name='ICT_bw')
    op.drop_column('ICT_bw', 'stamp')
    op.drop_column('ICT_bw', 'updt')
    op.drop_index(op.f('ix_GNI_updt'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_stamp'), table_name='GNI')
    op.drop_column('GNI', 'stamp')
    op.drop_column('GNI', 'updt')
    op.create_table('int_land',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('ctry', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_int_land_name', 'int_land', ['name'], unique=False)
    op.create_index('ix_int_land_lon', 'int_land', ['lon'], unique=False)
    op.create_index('ix_int_land_lat', 'int_land', ['lat'], unique=False)
    op.create_index('ix_int_land_ctry', 'int_land', ['ctry'], unique=False)
    op.create_table('car_land',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('ctry', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_car_land_name', 'car_land', ['name'], unique=False)
    op.create_index('ix_car_land_lon', 'car_land', ['lon'], unique=False)
    op.create_index('ix_car_land_lat', 'car_land', ['lat'], unique=False)
    op.create_index('ix_car_land_ctry', 'car_land', ['ctry'], unique=False)
    op.create_table('src_updt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('src', sa.VARCHAR(), nullable=True),
    sa.Column('updt', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_src_updt_updt', 'src_updt', ['updt'], unique=False)
    op.create_index('ix_src_updt_src', 'src_updt', ['src'], unique=False)
    op.drop_index(op.f('ix_land_updt'), table_name='land')
    op.drop_index(op.f('ix_land_stamp'), table_name='land')
    op.drop_index(op.f('ix_land_name'), table_name='land')
    op.drop_index(op.f('ix_land_lon'), table_name='land')
    op.drop_index(op.f('ix_land_lat'), table_name='land')
    op.drop_index(op.f('ix_land_ctry'), table_name='land')
    op.drop_index(op.f('ix_land_car'), table_name='land')
    op.drop_table('land')
    op.drop_index(op.f('ix_ixp_sub_ver'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_url_traf'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_traf'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_sub'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_stat'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_stamp'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_prts'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_name'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_mlpa'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_est'), table_name='ixp_sub')
    op.drop_index(op.f('ix_ixp_sub_ctry'), table_name='ixp_sub')
    op.drop_table('ixp_sub')
    op.drop_index(op.f('ix_ixp_mem_stamp'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_prfs'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_ping'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_peer'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_org'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_ipv6'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_ipv4'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_ip'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_fqdn'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_ctry'), table_name='ixp_mem')
    op.drop_index(op.f('ix_ixp_mem_asn'), table_name='ixp_mem')
    op.drop_table('ixp_mem')
    op.drop_index(op.f('ix_ixp_dir_url'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_updt'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_stat'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_stamp'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_prts'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_prfs'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_name'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_lon'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_lat'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_ipv6_avg'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_ipv4_pk'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_ipv4_avg'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_date'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_ctry'), table_name='ixp_dir')
    op.drop_index(op.f('ix_ixp_dir_city'), table_name='ixp_dir')
    op.drop_table('ixp_dir')
    # ### end Alembic commands ###
