"""Updated landing points  model

Revision ID: 4541869fe686
Revises: 630ebf85f964
Create Date: 2022-02-05 06:21:49.426986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4541869fe686'
down_revision = '630ebf85f964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegeography_landing', sa.Column('id_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_telegeography_landing_id_ref'), 'telegeography_landing', ['id_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegeography_landing_id_ref'), table_name='telegeography_landing')
    op.drop_column('telegeography_landing', 'id_ref')
    # ### end Alembic commands ###
