"""Updated Submarine Cable Landing Points model

Revision ID: 4e1a0f12b846
Revises: b69de78e7642
Create Date: 2021-12-25 15:18:27.804185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1a0f12b846'
down_revision = 'b69de78e7642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('uni', sa.String(), nullable=True))
    op.create_index(op.f('ix_land_uni'), 'land', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_uni'), table_name='land')
    op.drop_column('land', 'uni')
    # ### end Alembic commands ###
