"""Updated Wpop_density model

Revision ID: 630ebf85f964
Revises: 91a0741b636b
Create Date: 2022-02-05 03:47:23.762988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630ebf85f964'
down_revision = '91a0741b636b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wpop_density', sa.Column('url_tif', sa.String(), nullable=True))
    op.drop_index('ix_wpop_density_url_home', table_name='wpop_density')
    op.create_index(op.f('ix_wpop_density_url_tif'), 'wpop_density', ['url_tif'], unique=False)
    op.drop_column('wpop_density', 'url_home')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wpop_density', sa.Column('url_home', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_wpop_density_url_tif'), table_name='wpop_density')
    op.create_index('ix_wpop_density_url_home', 'wpop_density', ['url_home'], unique=False)
    op.drop_column('wpop_density', 'url_tif')
    # ### end Alembic commands ###
