"""Updated Submarine Cable Landing Points model

Revision ID: 6bec74d74967
Revises: 2709e836f731
Create Date: 2021-12-25 15:26:23.219117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec74d74967'
down_revision = '2709e836f731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('car', sa.String(), nullable=True))
    op.drop_index('ix_land_reg', table_name='land')
    op.create_index(op.f('ix_land_car'), 'land', ['car'], unique=False)
    op.drop_column('land', 'reg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('reg', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_land_car'), table_name='land')
    op.create_index('ix_land_reg', 'land', ['reg'], unique=False)
    op.drop_column('land', 'car')
    # ### end Alembic commands ###
