"""Updated Population Density model

Revision ID: 76092dcf08c1
Revises: 2e6074b71a9c
Create Date: 2021-12-26 06:21:41.601255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76092dcf08c1'
down_revision = '2e6074b71a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pop_dens', sa.Column('ctry', sa.String(), nullable=True))
    op.add_column('pop_dens', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_pop_dens_ctry'), 'pop_dens', ['ctry'], unique=False)
    op.create_index(op.f('ix_pop_dens_url'), 'pop_dens', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pop_dens_url'), table_name='pop_dens')
    op.drop_index(op.f('ix_pop_dens_ctry'), table_name='pop_dens')
    op.drop_column('pop_dens', 'url')
    op.drop_column('pop_dens', 'ctry')
    # ### end Alembic commands ###
