"""Added IXP models for PeeringDB source

Revision ID: 769ae13c931a
Revises: e9620828533a
Create Date: 2022-01-30 22:08:16.315273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769ae13c931a'
down_revision = 'e9620828533a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_fac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fac_id', sa.String(), nullable=True),
    sa.Column('net_id', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_long', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('sales_email', sa.String(), nullable=True),
    sa.Column('sales_phone', sa.String(), nullable=True),
    sa.Column('tech_email', sa.String(), nullable=True),
    sa.Column('tech_phone', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_fac_address1'), 'peer_fac', ['address1'], unique=False)
    op.create_index(op.f('ix_peer_fac_address2'), 'peer_fac', ['address2'], unique=False)
    op.create_index(op.f('ix_peer_fac_city'), 'peer_fac', ['city'], unique=False)
    op.create_index(op.f('ix_peer_fac_country'), 'peer_fac', ['country'], unique=False)
    op.create_index(op.f('ix_peer_fac_fac_id'), 'peer_fac', ['fac_id'], unique=False)
    op.create_index(op.f('ix_peer_fac_latitude'), 'peer_fac', ['latitude'], unique=False)
    op.create_index(op.f('ix_peer_fac_longitude'), 'peer_fac', ['longitude'], unique=False)
    op.create_index(op.f('ix_peer_fac_name'), 'peer_fac', ['name'], unique=False)
    op.create_index(op.f('ix_peer_fac_name_long'), 'peer_fac', ['name_long'], unique=False)
    op.create_index(op.f('ix_peer_fac_net_id'), 'peer_fac', ['net_id'], unique=False)
    op.create_index(op.f('ix_peer_fac_org_name'), 'peer_fac', ['org_name'], unique=False)
    op.create_index(op.f('ix_peer_fac_sales_email'), 'peer_fac', ['sales_email'], unique=False)
    op.create_index(op.f('ix_peer_fac_sales_phone'), 'peer_fac', ['sales_phone'], unique=False)
    op.create_index(op.f('ix_peer_fac_stamp'), 'peer_fac', ['stamp'], unique=False)
    op.create_index(op.f('ix_peer_fac_state'), 'peer_fac', ['state'], unique=False)
    op.create_index(op.f('ix_peer_fac_status'), 'peer_fac', ['status'], unique=False)
    op.create_index(op.f('ix_peer_fac_tech_email'), 'peer_fac', ['tech_email'], unique=False)
    op.create_index(op.f('ix_peer_fac_tech_phone'), 'peer_fac', ['tech_phone'], unique=False)
    op.create_index(op.f('ix_peer_fac_updated'), 'peer_fac', ['updated'], unique=False)
    op.create_index(op.f('ix_peer_fac_website'), 'peer_fac', ['website'], unique=False)
    op.create_index(op.f('ix_peer_fac_zipcode'), 'peer_fac', ['zipcode'], unique=False)
    op.create_table('peer_ix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ix_id', sa.String(), nullable=True),
    sa.Column('fac_id', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_long', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('proto_unicast', sa.String(), nullable=True),
    sa.Column('proto_multicast', sa.String(), nullable=True),
    sa.Column('proto_ipv6', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('url_stats', sa.String(), nullable=True),
    sa.Column('tech_email', sa.String(), nullable=True),
    sa.Column('tech_phone', sa.String(), nullable=True),
    sa.Column('policy_email', sa.String(), nullable=True),
    sa.Column('policy_phone', sa.String(), nullable=True),
    sa.Column('sales_phone', sa.String(), nullable=True),
    sa.Column('sales_email', sa.String(), nullable=True),
    sa.Column('service_level', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_ix_city'), 'peer_ix', ['city'], unique=False)
    op.create_index(op.f('ix_peer_ix_country'), 'peer_ix', ['country'], unique=False)
    op.create_index(op.f('ix_peer_ix_fac_id'), 'peer_ix', ['fac_id'], unique=False)
    op.create_index(op.f('ix_peer_ix_ix_id'), 'peer_ix', ['ix_id'], unique=False)
    op.create_index(op.f('ix_peer_ix_media'), 'peer_ix', ['media'], unique=False)
    op.create_index(op.f('ix_peer_ix_name'), 'peer_ix', ['name'], unique=False)
    op.create_index(op.f('ix_peer_ix_name_long'), 'peer_ix', ['name_long'], unique=False)
    op.create_index(op.f('ix_peer_ix_org_name'), 'peer_ix', ['org_name'], unique=False)
    op.create_index(op.f('ix_peer_ix_policy_email'), 'peer_ix', ['policy_email'], unique=False)
    op.create_index(op.f('ix_peer_ix_policy_phone'), 'peer_ix', ['policy_phone'], unique=False)
    op.create_index(op.f('ix_peer_ix_proto_ipv6'), 'peer_ix', ['proto_ipv6'], unique=False)
    op.create_index(op.f('ix_peer_ix_proto_multicast'), 'peer_ix', ['proto_multicast'], unique=False)
    op.create_index(op.f('ix_peer_ix_proto_unicast'), 'peer_ix', ['proto_unicast'], unique=False)
    op.create_index(op.f('ix_peer_ix_sales_email'), 'peer_ix', ['sales_email'], unique=False)
    op.create_index(op.f('ix_peer_ix_sales_phone'), 'peer_ix', ['sales_phone'], unique=False)
    op.create_index(op.f('ix_peer_ix_service_level'), 'peer_ix', ['service_level'], unique=False)
    op.create_index(op.f('ix_peer_ix_stamp'), 'peer_ix', ['stamp'], unique=False)
    op.create_index(op.f('ix_peer_ix_status'), 'peer_ix', ['status'], unique=False)
    op.create_index(op.f('ix_peer_ix_tech_email'), 'peer_ix', ['tech_email'], unique=False)
    op.create_index(op.f('ix_peer_ix_tech_phone'), 'peer_ix', ['tech_phone'], unique=False)
    op.create_index(op.f('ix_peer_ix_terms'), 'peer_ix', ['terms'], unique=False)
    op.create_index(op.f('ix_peer_ix_updated'), 'peer_ix', ['updated'], unique=False)
    op.create_index(op.f('ix_peer_ix_url_stats'), 'peer_ix', ['url_stats'], unique=False)
    op.create_index(op.f('ix_peer_ix_website'), 'peer_ix', ['website'], unique=False)
    op.create_table('peer_net',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('net_id', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_long', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('looking_glass', sa.String(), nullable=True),
    sa.Column('route_server', sa.String(), nullable=True),
    sa.Column('irr_as_set', sa.String(), nullable=True),
    sa.Column('info_type', sa.String(), nullable=True),
    sa.Column('info_prefixes4', sa.String(), nullable=True),
    sa.Column('info_prefixes6', sa.String(), nullable=True),
    sa.Column('info_traffic', sa.String(), nullable=True),
    sa.Column('info_ratio', sa.String(), nullable=True),
    sa.Column('info_scope', sa.String(), nullable=True),
    sa.Column('info_unicast', sa.String(), nullable=True),
    sa.Column('info_multicast', sa.String(), nullable=True),
    sa.Column('info_ipv6', sa.String(), nullable=True),
    sa.Column('info_never_via_route_servers', sa.String(), nullable=True),
    sa.Column('policy_url', sa.String(), nullable=True),
    sa.Column('policy_general', sa.String(), nullable=True),
    sa.Column('policy_locations', sa.String(), nullable=True),
    sa.Column('policy_contracts', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_net_asn'), 'peer_net', ['asn'], unique=False)
    op.create_index(op.f('ix_peer_net_info_ipv6'), 'peer_net', ['info_ipv6'], unique=False)
    op.create_index(op.f('ix_peer_net_info_multicast'), 'peer_net', ['info_multicast'], unique=False)
    op.create_index(op.f('ix_peer_net_info_never_via_route_servers'), 'peer_net', ['info_never_via_route_servers'], unique=False)
    op.create_index(op.f('ix_peer_net_info_prefixes4'), 'peer_net', ['info_prefixes4'], unique=False)
    op.create_index(op.f('ix_peer_net_info_prefixes6'), 'peer_net', ['info_prefixes6'], unique=False)
    op.create_index(op.f('ix_peer_net_info_ratio'), 'peer_net', ['info_ratio'], unique=False)
    op.create_index(op.f('ix_peer_net_info_scope'), 'peer_net', ['info_scope'], unique=False)
    op.create_index(op.f('ix_peer_net_info_traffic'), 'peer_net', ['info_traffic'], unique=False)
    op.create_index(op.f('ix_peer_net_info_type'), 'peer_net', ['info_type'], unique=False)
    op.create_index(op.f('ix_peer_net_info_unicast'), 'peer_net', ['info_unicast'], unique=False)
    op.create_index(op.f('ix_peer_net_irr_as_set'), 'peer_net', ['irr_as_set'], unique=False)
    op.create_index(op.f('ix_peer_net_looking_glass'), 'peer_net', ['looking_glass'], unique=False)
    op.create_index(op.f('ix_peer_net_name'), 'peer_net', ['name'], unique=False)
    op.create_index(op.f('ix_peer_net_name_long'), 'peer_net', ['name_long'], unique=False)
    op.create_index(op.f('ix_peer_net_net_id'), 'peer_net', ['net_id'], unique=False)
    op.create_index(op.f('ix_peer_net_org_name'), 'peer_net', ['org_name'], unique=False)
    op.create_index(op.f('ix_peer_net_policy_contracts'), 'peer_net', ['policy_contracts'], unique=False)
    op.create_index(op.f('ix_peer_net_policy_general'), 'peer_net', ['policy_general'], unique=False)
    op.create_index(op.f('ix_peer_net_policy_locations'), 'peer_net', ['policy_locations'], unique=False)
    op.create_index(op.f('ix_peer_net_policy_url'), 'peer_net', ['policy_url'], unique=False)
    op.create_index(op.f('ix_peer_net_route_server'), 'peer_net', ['route_server'], unique=False)
    op.create_index(op.f('ix_peer_net_stamp'), 'peer_net', ['stamp'], unique=False)
    op.create_index(op.f('ix_peer_net_status'), 'peer_net', ['status'], unique=False)
    op.create_index(op.f('ix_peer_net_updated'), 'peer_net', ['updated'], unique=False)
    op.create_index(op.f('ix_peer_net_website'), 'peer_net', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_net_website'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_updated'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_status'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_stamp'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_route_server'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_policy_url'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_policy_locations'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_policy_general'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_policy_contracts'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_org_name'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_net_id'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_name_long'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_name'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_looking_glass'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_irr_as_set'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_unicast'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_type'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_traffic'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_scope'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_ratio'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_prefixes6'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_prefixes4'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_never_via_route_servers'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_multicast'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_info_ipv6'), table_name='peer_net')
    op.drop_index(op.f('ix_peer_net_asn'), table_name='peer_net')
    op.drop_table('peer_net')
    op.drop_index(op.f('ix_peer_ix_website'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_url_stats'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_updated'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_terms'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_tech_phone'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_tech_email'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_status'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_stamp'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_service_level'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_sales_phone'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_sales_email'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_proto_unicast'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_proto_multicast'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_proto_ipv6'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_policy_phone'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_policy_email'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_org_name'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_name_long'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_name'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_media'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_ix_id'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_fac_id'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_country'), table_name='peer_ix')
    op.drop_index(op.f('ix_peer_ix_city'), table_name='peer_ix')
    op.drop_table('peer_ix')
    op.drop_index(op.f('ix_peer_fac_zipcode'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_website'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_updated'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_tech_phone'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_tech_email'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_status'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_state'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_stamp'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_sales_phone'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_sales_email'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_org_name'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_net_id'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_name_long'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_name'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_longitude'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_latitude'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_fac_id'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_country'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_city'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_address2'), table_name='peer_fac')
    op.drop_index(op.f('ix_peer_fac_address1'), table_name='peer_fac')
    op.drop_table('peer_fac')
    # ### end Alembic commands ###
