"""Updated uni data type in tables

Revision ID: 90bb67e3658c
Revises: b28965dbe8af
Create Date: 2022-01-03 11:01:11.765595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bb67e3658c'
down_revision = 'b28965dbe8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ICT_mob', sa.Column('gy', sa.Float(), nullable=True))
    op.create_index(op.f('ix_ICT_mob_gy'), 'ICT_mob', ['gy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ICT_mob_gy'), table_name='ICT_mob')
    op.drop_column('ICT_mob', 'gy')
    # ### end Alembic commands ###
