"""Add submarine cables model

Revision ID: 91a0741b636b
Revises: 09512d00b2c0
Create Date: 2022-02-05 02:58:19.901821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a0741b636b'
down_revision = '09512d00b2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegeography_submarine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('land_pts', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('rfs', sa.String(), nullable=True),
    sa.Column('suppliers', sa.String(), nullable=True),
    sa.Column('owners', sa.String(), nullable=True),
    sa.Column('url_home', sa.String(), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('stamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegeography_submarine_geometry'), 'telegeography_submarine', ['geometry'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_land_pts'), 'telegeography_submarine', ['land_pts'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_length'), 'telegeography_submarine', ['length'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_name'), 'telegeography_submarine', ['name'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_owners'), 'telegeography_submarine', ['owners'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_rfs'), 'telegeography_submarine', ['rfs'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_source'), 'telegeography_submarine', ['source'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_stamp'), 'telegeography_submarine', ['stamp'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_status'), 'telegeography_submarine', ['status'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_suppliers'), 'telegeography_submarine', ['suppliers'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_updated'), 'telegeography_submarine', ['updated'], unique=False)
    op.create_index(op.f('ix_telegeography_submarine_url_home'), 'telegeography_submarine', ['url_home'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegeography_submarine_url_home'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_updated'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_suppliers'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_status'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_stamp'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_source'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_rfs'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_owners'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_name'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_length'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_land_pts'), table_name='telegeography_submarine')
    op.drop_index(op.f('ix_telegeography_submarine_geometry'), table_name='telegeography_submarine')
    op.drop_table('telegeography_submarine')
    # ### end Alembic commands ###
