"""Indicators models merged

Revision ID: 949b4d4f4a6f
Revises: 769ae13c931a
Create Date: 2022-01-31 03:22:39.211627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949b4d4f4a6f'
down_revision = '769ae13c931a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('fix', sa.Float(), nullable=True),
    sa.Column('mob', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('bw', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_bw'), 'indicators', ['bw'], unique=False)
    op.create_index(op.f('ix_indicators_ctry'), 'indicators', ['ctry'], unique=False)
    op.create_index(op.f('ix_indicators_fix'), 'indicators', ['fix'], unique=False)
    op.create_index(op.f('ix_indicators_mob'), 'indicators', ['mob'], unique=False)
    op.create_index(op.f('ix_indicators_per'), 'indicators', ['per'], unique=False)
    op.create_index(op.f('ix_indicators_year'), 'indicators', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_year'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_per'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_mob'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_fix'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_ctry'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_bw'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
