"""Updated IXP member details in models

Revision ID: af56d0f3f3f1
Revises: ebbbce5d9e73
Create Date: 2021-12-24 06:32:26.670113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af56d0f3f3f1'
down_revision = 'ebbbce5d9e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ixp_mem', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ixp_mem_uni'), 'ixp_mem', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ixp_mem_uni'), table_name='ixp_mem')
    op.drop_column('ixp_mem', 'uni')
    # ### end Alembic commands ###
