"""Updated uni data type in tables

Revision ID: b28965dbe8af
Revises: 0de913e2c09b
Create Date: 2022-01-03 11:00:16.928816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28965dbe8af'
down_revision = '0de913e2c09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ICT_mob_gy', table_name='ICT_mob')
    op.drop_column('ICT_mob', 'gy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ICT_mob', sa.Column('gy', sa.FLOAT(), nullable=True))
    op.create_index('ix_ICT_mob_gy', 'ICT_mob', ['gy'], unique=False)
    # ### end Alembic commands ###
