"""Updated Speed index models

Revision ID: b69de78e7642
Revises: 1ddba62d0e58
Create Date: 2021-12-25 00:09:42.128677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69de78e7642'
down_revision = '1ddba62d0e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_br', sa.Column('uni', sa.String(), nullable=True))
    op.create_index(op.f('ix_fixed_br_uni'), 'fixed_br', ['uni'], unique=False)
    op.add_column('mob_br', sa.Column('uni', sa.String(), nullable=True))
    op.create_index(op.f('ix_mob_br_uni'), 'mob_br', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mob_br_uni'), table_name='mob_br')
    op.drop_column('mob_br', 'uni')
    op.drop_index(op.f('ix_fixed_br_uni'), table_name='fixed_br')
    op.drop_column('fixed_br', 'uni')
    # ### end Alembic commands ###
