"""Added cables to Landing Points model

Revision ID: b847c0025959
Revises: 385f20cc0509
Create Date: 2021-12-30 10:28:20.824898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b847c0025959'
down_revision = '385f20cc0509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('cab', sa.String(), nullable=True))
    op.create_index(op.f('ix_land_cab'), 'land', ['cab'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_cab'), table_name='land')
    op.drop_column('land', 'cab')
    # ### end Alembic commands ###
