"""Modified reg field in Tld model

Revision ID: d87d4d1ec532
Revises: 002ea6028992
Create Date: 2021-12-31 05:19:49.902822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87d4d1ec532'
down_revision = '002ea6028992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tld', sa.Column('dates', sa.String(), nullable=True))
    op.create_index(op.f('ix_tld_dates'), 'tld', ['dates'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tld_dates'), table_name='tld')
    op.drop_column('tld', 'dates')
    # ### end Alembic commands ###
