"""Updated Wpop_density

Revision ID: dbfb45f092bc
Revises: 4541869fe686
Create Date: 2022-03-17 15:20:18.508407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfb45f092bc'
down_revision = '4541869fe686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wpop_density', sa.Column('max_lat', sa.Float(), nullable=True))
    op.add_column('wpop_density', sa.Column('max_lon', sa.Float(), nullable=True))
    op.add_column('wpop_density', sa.Column('min_lat', sa.Float(), nullable=True))
    op.add_column('wpop_density', sa.Column('min_lon', sa.Float(), nullable=True))
    op.create_index(op.f('ix_wpop_density_max_lat'), 'wpop_density', ['max_lat'], unique=False)
    op.create_index(op.f('ix_wpop_density_max_lon'), 'wpop_density', ['max_lon'], unique=False)
    op.create_index(op.f('ix_wpop_density_min_lat'), 'wpop_density', ['min_lat'], unique=False)
    op.create_index(op.f('ix_wpop_density_min_lon'), 'wpop_density', ['min_lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wpop_density_min_lon'), table_name='wpop_density')
    op.drop_index(op.f('ix_wpop_density_min_lat'), table_name='wpop_density')
    op.drop_index(op.f('ix_wpop_density_max_lon'), table_name='wpop_density')
    op.drop_index(op.f('ix_wpop_density_max_lat'), table_name='wpop_density')
    op.drop_column('wpop_density', 'min_lon')
    op.drop_column('wpop_density', 'min_lat')
    op.drop_column('wpop_density', 'max_lon')
    op.drop_column('wpop_density', 'max_lat')
    # ### end Alembic commands ###
