"""Change mnth to date in Mob_br and Fixed_br models

Revision ID: e9620828533a
Revises: 90bb67e3658c
Create Date: 2022-01-03 13:20:37.591444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9620828533a'
down_revision = '90bb67e3658c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_br', sa.Column('date', sa.String(), nullable=True))
    op.drop_index('ix_fixed_br_mnth', table_name='fixed_br')
    op.create_index(op.f('ix_fixed_br_date'), 'fixed_br', ['date'], unique=False)
    op.drop_column('fixed_br', 'mnth')
    op.add_column('mob_br', sa.Column('date', sa.String(), nullable=True))
    op.drop_index('ix_mob_br_mnth', table_name='mob_br')
    op.create_index(op.f('ix_mob_br_date'), 'mob_br', ['date'], unique=False)
    op.drop_column('mob_br', 'mnth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_br', sa.Column('mnth', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_mob_br_date'), table_name='mob_br')
    op.create_index('ix_mob_br_mnth', 'mob_br', ['mnth'], unique=False)
    op.drop_column('mob_br', 'date')
    op.add_column('fixed_br', sa.Column('mnth', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_fixed_br_date'), table_name='fixed_br')
    op.create_index('ix_fixed_br_mnth', 'fixed_br', ['mnth'], unique=False)
    op.drop_column('fixed_br', 'date')
    # ### end Alembic commands ###
