"""Updated IXP in models

Revision ID: ebbbce5d9e73
Revises: 28d4b7fda907
Create Date: 2021-12-24 06:18:58.240703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbbce5d9e73'
down_revision = '28d4b7fda907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ixp_dir', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ixp_dir_uni'), 'ixp_dir', ['uni'], unique=False)
    op.add_column('ixp_sub', sa.Column('uni', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ixp_sub_uni'), 'ixp_sub', ['uni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ixp_sub_uni'), table_name='ixp_sub')
    op.drop_column('ixp_sub', 'uni')
    op.drop_index(op.f('ix_ixp_dir_uni'), table_name='ixp_dir')
    op.drop_column('ixp_dir', 'uni')
    # ### end Alembic commands ###
