"""Added long IXP name to IXP_sub model

Revision ID: eec01ccb2fcb
Revises: b847c0025959
Create Date: 2021-12-30 16:27:48.811299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec01ccb2fcb'
down_revision = 'b847c0025959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ixp_sub', sa.Column('name_lng', sa.String(), nullable=True))
    op.create_index(op.f('ix_ixp_sub_name_lng'), 'ixp_sub', ['name_lng'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ixp_sub_name_lng'), table_name='ixp_sub')
    op.drop_column('ixp_sub', 'name_lng')
    # ### end Alembic commands ###
