"""Removed other indicators tables

Revision ID: fb326181bbc6
Revises: 949b4d4f4a6f
Create Date: 2022-01-31 03:45:07.045981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb326181bbc6'
down_revision = '949b4d4f4a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('updt', sa.String(), nullable=True))
    op.add_column('indicators', sa.Column('stamp', sa.String(), nullable=True))
    op.create_index(op.f('ix_indicators_stamp'), 'indicators', ['stamp'], unique=False)
    op.create_index(op.f('ix_indicators_updt'), 'indicators', ['updt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_updt'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_stamp'), table_name='indicators')
    op.drop_column('indicators', 'stamp')
    op.drop_column('indicators', 'updt')
    # ### end Alembic commands ###
