"""Database structure

Revision ID: ff0f8fa69600
Revises: 
Create Date: 2021-12-20 05:29:01.984627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0f8fa69600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GNI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fix', sa.Float(), nullable=True),
    sa.Column('mob', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GNI_ctry'), 'GNI', ['ctry'], unique=False)
    op.create_index(op.f('ix_GNI_fix'), 'GNI', ['fix'], unique=False)
    op.create_index(op.f('ix_GNI_high'), 'GNI', ['high'], unique=False)
    op.create_index(op.f('ix_GNI_low'), 'GNI', ['low'], unique=False)
    op.create_index(op.f('ix_GNI_mob'), 'GNI', ['mob'], unique=False)
    op.create_index(op.f('ix_GNI_year'), 'GNI', ['year'], unique=False)
    op.create_table('ICT_bw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yrs', sa.Integer(), nullable=True),
    sa.Column('ai', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('bs', sa.Float(), nullable=True),
    sa.Column('bb', sa.Float(), nullable=True),
    sa.Column('bz', sa.Float(), nullable=True),
    sa.Column('bm', sa.Float(), nullable=True),
    sa.Column('vg', sa.Float(), nullable=True),
    sa.Column('ky', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('gd', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('ht', sa.Float(), nullable=True),
    sa.Column('jm', sa.Float(), nullable=True),
    sa.Column('ms', sa.Float(), nullable=True),
    sa.Column('kn', sa.Float(), nullable=True),
    sa.Column('lc', sa.Float(), nullable=True),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('tt', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ICT_bw_ag'), 'ICT_bw', ['ag'], unique=False)
    op.create_index(op.f('ix_ICT_bw_ai'), 'ICT_bw', ['ai'], unique=False)
    op.create_index(op.f('ix_ICT_bw_bb'), 'ICT_bw', ['bb'], unique=False)
    op.create_index(op.f('ix_ICT_bw_bm'), 'ICT_bw', ['bm'], unique=False)
    op.create_index(op.f('ix_ICT_bw_bs'), 'ICT_bw', ['bs'], unique=False)
    op.create_index(op.f('ix_ICT_bw_bz'), 'ICT_bw', ['bz'], unique=False)
    op.create_index(op.f('ix_ICT_bw_dm'), 'ICT_bw', ['dm'], unique=False)
    op.create_index(op.f('ix_ICT_bw_gd'), 'ICT_bw', ['gd'], unique=False)
    op.create_index(op.f('ix_ICT_bw_gy'), 'ICT_bw', ['gy'], unique=False)
    op.create_index(op.f('ix_ICT_bw_ht'), 'ICT_bw', ['ht'], unique=False)
    op.create_index(op.f('ix_ICT_bw_jm'), 'ICT_bw', ['jm'], unique=False)
    op.create_index(op.f('ix_ICT_bw_kn'), 'ICT_bw', ['kn'], unique=False)
    op.create_index(op.f('ix_ICT_bw_ky'), 'ICT_bw', ['ky'], unique=False)
    op.create_index(op.f('ix_ICT_bw_lc'), 'ICT_bw', ['lc'], unique=False)
    op.create_index(op.f('ix_ICT_bw_ms'), 'ICT_bw', ['ms'], unique=False)
    op.create_index(op.f('ix_ICT_bw_sr'), 'ICT_bw', ['sr'], unique=False)
    op.create_index(op.f('ix_ICT_bw_tc'), 'ICT_bw', ['tc'], unique=False)
    op.create_index(op.f('ix_ICT_bw_tt'), 'ICT_bw', ['tt'], unique=False)
    op.create_index(op.f('ix_ICT_bw_vc'), 'ICT_bw', ['vc'], unique=False)
    op.create_index(op.f('ix_ICT_bw_vg'), 'ICT_bw', ['vg'], unique=False)
    op.create_index(op.f('ix_ICT_bw_yrs'), 'ICT_bw', ['yrs'], unique=False)
    op.create_table('ICT_fix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yrs', sa.Integer(), nullable=True),
    sa.Column('ai', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('bs', sa.Float(), nullable=True),
    sa.Column('bb', sa.Float(), nullable=True),
    sa.Column('bz', sa.Float(), nullable=True),
    sa.Column('bm', sa.Float(), nullable=True),
    sa.Column('vg', sa.Float(), nullable=True),
    sa.Column('ky', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('gd', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('ht', sa.Float(), nullable=True),
    sa.Column('jm', sa.Float(), nullable=True),
    sa.Column('ms', sa.Float(), nullable=True),
    sa.Column('kn', sa.Float(), nullable=True),
    sa.Column('lc', sa.Float(), nullable=True),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('tt', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ICT_fix_ag'), 'ICT_fix', ['ag'], unique=False)
    op.create_index(op.f('ix_ICT_fix_ai'), 'ICT_fix', ['ai'], unique=False)
    op.create_index(op.f('ix_ICT_fix_bb'), 'ICT_fix', ['bb'], unique=False)
    op.create_index(op.f('ix_ICT_fix_bm'), 'ICT_fix', ['bm'], unique=False)
    op.create_index(op.f('ix_ICT_fix_bs'), 'ICT_fix', ['bs'], unique=False)
    op.create_index(op.f('ix_ICT_fix_bz'), 'ICT_fix', ['bz'], unique=False)
    op.create_index(op.f('ix_ICT_fix_dm'), 'ICT_fix', ['dm'], unique=False)
    op.create_index(op.f('ix_ICT_fix_gd'), 'ICT_fix', ['gd'], unique=False)
    op.create_index(op.f('ix_ICT_fix_gy'), 'ICT_fix', ['gy'], unique=False)
    op.create_index(op.f('ix_ICT_fix_ht'), 'ICT_fix', ['ht'], unique=False)
    op.create_index(op.f('ix_ICT_fix_jm'), 'ICT_fix', ['jm'], unique=False)
    op.create_index(op.f('ix_ICT_fix_kn'), 'ICT_fix', ['kn'], unique=False)
    op.create_index(op.f('ix_ICT_fix_ky'), 'ICT_fix', ['ky'], unique=False)
    op.create_index(op.f('ix_ICT_fix_lc'), 'ICT_fix', ['lc'], unique=False)
    op.create_index(op.f('ix_ICT_fix_ms'), 'ICT_fix', ['ms'], unique=False)
    op.create_index(op.f('ix_ICT_fix_sr'), 'ICT_fix', ['sr'], unique=False)
    op.create_index(op.f('ix_ICT_fix_tc'), 'ICT_fix', ['tc'], unique=False)
    op.create_index(op.f('ix_ICT_fix_tt'), 'ICT_fix', ['tt'], unique=False)
    op.create_index(op.f('ix_ICT_fix_vc'), 'ICT_fix', ['vc'], unique=False)
    op.create_index(op.f('ix_ICT_fix_vg'), 'ICT_fix', ['vg'], unique=False)
    op.create_index(op.f('ix_ICT_fix_yrs'), 'ICT_fix', ['yrs'], unique=False)
    op.create_table('ICT_mob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yrs', sa.Integer(), nullable=True),
    sa.Column('ai', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('bs', sa.Float(), nullable=True),
    sa.Column('bb', sa.Float(), nullable=True),
    sa.Column('bz', sa.Float(), nullable=True),
    sa.Column('bm', sa.Float(), nullable=True),
    sa.Column('vg', sa.Float(), nullable=True),
    sa.Column('ky', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('gd', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('ht', sa.Float(), nullable=True),
    sa.Column('jm', sa.Float(), nullable=True),
    sa.Column('ms', sa.Float(), nullable=True),
    sa.Column('kn', sa.Float(), nullable=True),
    sa.Column('lc', sa.Float(), nullable=True),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('tt', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ICT_mob_ag'), 'ICT_mob', ['ag'], unique=False)
    op.create_index(op.f('ix_ICT_mob_ai'), 'ICT_mob', ['ai'], unique=False)
    op.create_index(op.f('ix_ICT_mob_bb'), 'ICT_mob', ['bb'], unique=False)
    op.create_index(op.f('ix_ICT_mob_bm'), 'ICT_mob', ['bm'], unique=False)
    op.create_index(op.f('ix_ICT_mob_bs'), 'ICT_mob', ['bs'], unique=False)
    op.create_index(op.f('ix_ICT_mob_bz'), 'ICT_mob', ['bz'], unique=False)
    op.create_index(op.f('ix_ICT_mob_dm'), 'ICT_mob', ['dm'], unique=False)
    op.create_index(op.f('ix_ICT_mob_gd'), 'ICT_mob', ['gd'], unique=False)
    op.create_index(op.f('ix_ICT_mob_gy'), 'ICT_mob', ['gy'], unique=False)
    op.create_index(op.f('ix_ICT_mob_ht'), 'ICT_mob', ['ht'], unique=False)
    op.create_index(op.f('ix_ICT_mob_jm'), 'ICT_mob', ['jm'], unique=False)
    op.create_index(op.f('ix_ICT_mob_kn'), 'ICT_mob', ['kn'], unique=False)
    op.create_index(op.f('ix_ICT_mob_ky'), 'ICT_mob', ['ky'], unique=False)
    op.create_index(op.f('ix_ICT_mob_lc'), 'ICT_mob', ['lc'], unique=False)
    op.create_index(op.f('ix_ICT_mob_ms'), 'ICT_mob', ['ms'], unique=False)
    op.create_index(op.f('ix_ICT_mob_sr'), 'ICT_mob', ['sr'], unique=False)
    op.create_index(op.f('ix_ICT_mob_tc'), 'ICT_mob', ['tc'], unique=False)
    op.create_index(op.f('ix_ICT_mob_tt'), 'ICT_mob', ['tt'], unique=False)
    op.create_index(op.f('ix_ICT_mob_vc'), 'ICT_mob', ['vc'], unique=False)
    op.create_index(op.f('ix_ICT_mob_vg'), 'ICT_mob', ['vg'], unique=False)
    op.create_index(op.f('ix_ICT_mob_yrs'), 'ICT_mob', ['yrs'], unique=False)
    op.create_table('ICT_per',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yrs', sa.Integer(), nullable=True),
    sa.Column('ai', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('bs', sa.Float(), nullable=True),
    sa.Column('bb', sa.Float(), nullable=True),
    sa.Column('bz', sa.Float(), nullable=True),
    sa.Column('bm', sa.Float(), nullable=True),
    sa.Column('vg', sa.Float(), nullable=True),
    sa.Column('ky', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('gd', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('ht', sa.Float(), nullable=True),
    sa.Column('jm', sa.Float(), nullable=True),
    sa.Column('ms', sa.Float(), nullable=True),
    sa.Column('kn', sa.Float(), nullable=True),
    sa.Column('lc', sa.Float(), nullable=True),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('tt', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ICT_per_ag'), 'ICT_per', ['ag'], unique=False)
    op.create_index(op.f('ix_ICT_per_ai'), 'ICT_per', ['ai'], unique=False)
    op.create_index(op.f('ix_ICT_per_bb'), 'ICT_per', ['bb'], unique=False)
    op.create_index(op.f('ix_ICT_per_bm'), 'ICT_per', ['bm'], unique=False)
    op.create_index(op.f('ix_ICT_per_bs'), 'ICT_per', ['bs'], unique=False)
    op.create_index(op.f('ix_ICT_per_bz'), 'ICT_per', ['bz'], unique=False)
    op.create_index(op.f('ix_ICT_per_dm'), 'ICT_per', ['dm'], unique=False)
    op.create_index(op.f('ix_ICT_per_gd'), 'ICT_per', ['gd'], unique=False)
    op.create_index(op.f('ix_ICT_per_gy'), 'ICT_per', ['gy'], unique=False)
    op.create_index(op.f('ix_ICT_per_ht'), 'ICT_per', ['ht'], unique=False)
    op.create_index(op.f('ix_ICT_per_jm'), 'ICT_per', ['jm'], unique=False)
    op.create_index(op.f('ix_ICT_per_kn'), 'ICT_per', ['kn'], unique=False)
    op.create_index(op.f('ix_ICT_per_ky'), 'ICT_per', ['ky'], unique=False)
    op.create_index(op.f('ix_ICT_per_lc'), 'ICT_per', ['lc'], unique=False)
    op.create_index(op.f('ix_ICT_per_ms'), 'ICT_per', ['ms'], unique=False)
    op.create_index(op.f('ix_ICT_per_sr'), 'ICT_per', ['sr'], unique=False)
    op.create_index(op.f('ix_ICT_per_tc'), 'ICT_per', ['tc'], unique=False)
    op.create_index(op.f('ix_ICT_per_tt'), 'ICT_per', ['tt'], unique=False)
    op.create_index(op.f('ix_ICT_per_vc'), 'ICT_per', ['vc'], unique=False)
    op.create_index(op.f('ix_ICT_per_vg'), 'ICT_per', ['vg'], unique=False)
    op.create_index(op.f('ix_ICT_per_yrs'), 'ICT_per', ['yrs'], unique=False)
    op.create_table('PPP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fix', sa.Float(), nullable=True),
    sa.Column('mob', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PPP_ctry'), 'PPP', ['ctry'], unique=False)
    op.create_index(op.f('ix_PPP_fix'), 'PPP', ['fix'], unique=False)
    op.create_index(op.f('ix_PPP_high'), 'PPP', ['high'], unique=False)
    op.create_index(op.f('ix_PPP_low'), 'PPP', ['low'], unique=False)
    op.create_index(op.f('ix_PPP_mob'), 'PPP', ['mob'], unique=False)
    op.create_index(op.f('ix_PPP_year'), 'PPP', ['year'], unique=False)
    op.create_table('USD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fix', sa.Float(), nullable=True),
    sa.Column('mob', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USD_ctry'), 'USD', ['ctry'], unique=False)
    op.create_index(op.f('ix_USD_fix'), 'USD', ['fix'], unique=False)
    op.create_index(op.f('ix_USD_high'), 'USD', ['high'], unique=False)
    op.create_index(op.f('ix_USD_low'), 'USD', ['low'], unique=False)
    op.create_index(op.f('ix_USD_mob'), 'USD', ['mob'], unique=False)
    op.create_index(op.f('ix_USD_year'), 'USD', ['year'], unique=False)
    op.create_table('car_land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_land_ctry'), 'car_land', ['ctry'], unique=False)
    op.create_index(op.f('ix_car_land_lat'), 'car_land', ['lat'], unique=False)
    op.create_index(op.f('ix_car_land_lon'), 'car_land', ['lon'], unique=False)
    op.create_index(op.f('ix_car_land_name'), 'car_land', ['name'], unique=False)
    op.create_table('fixed_br',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mnth', sa.String(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('dls', sa.Float(), nullable=True),
    sa.Column('ups', sa.Float(), nullable=True),
    sa.Column('ltcy', sa.Float(), nullable=True),
    sa.Column('jitt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_br_ctry'), 'fixed_br', ['ctry'], unique=False)
    op.create_index(op.f('ix_fixed_br_dls'), 'fixed_br', ['dls'], unique=False)
    op.create_index(op.f('ix_fixed_br_jitt'), 'fixed_br', ['jitt'], unique=False)
    op.create_index(op.f('ix_fixed_br_ltcy'), 'fixed_br', ['ltcy'], unique=False)
    op.create_index(op.f('ix_fixed_br_mnth'), 'fixed_br', ['mnth'], unique=False)
    op.create_index(op.f('ix_fixed_br_ups'), 'fixed_br', ['ups'], unique=False)
    op.create_table('gen_pop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry_', sa.String(), nullable=True),
    sa.Column('gen', sa.String(), nullable=True),
    sa.Column('cur', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('land', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('pop', sa.String(), nullable=True),
    sa.Column('urb', sa.String(), nullable=True),
    sa.Column('elec', sa.String(), nullable=True),
    sa.Column('lab', sa.String(), nullable=True),
    sa.Column('occ', sa.String(), nullable=True),
    sa.Column('unem', sa.String(), nullable=True),
    sa.Column('pov', sa.String(), nullable=True),
    sa.Column('lit', sa.String(), nullable=True),
    sa.Column('updt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gen_pop_area'), 'gen_pop', ['area'], unique=False)
    op.create_index(op.f('ix_gen_pop_ctry_'), 'gen_pop', ['ctry_'], unique=False)
    op.create_index(op.f('ix_gen_pop_cur'), 'gen_pop', ['cur'], unique=False)
    op.create_index(op.f('ix_gen_pop_elec'), 'gen_pop', ['elec'], unique=False)
    op.create_index(op.f('ix_gen_pop_gen'), 'gen_pop', ['gen'], unique=False)
    op.create_index(op.f('ix_gen_pop_lab'), 'gen_pop', ['lab'], unique=False)
    op.create_index(op.f('ix_gen_pop_land'), 'gen_pop', ['land'], unique=False)
    op.create_index(op.f('ix_gen_pop_lang'), 'gen_pop', ['lang'], unique=False)
    op.create_index(op.f('ix_gen_pop_lit'), 'gen_pop', ['lit'], unique=False)
    op.create_index(op.f('ix_gen_pop_occ'), 'gen_pop', ['occ'], unique=False)
    op.create_index(op.f('ix_gen_pop_pop'), 'gen_pop', ['pop'], unique=False)
    op.create_index(op.f('ix_gen_pop_pov'), 'gen_pop', ['pov'], unique=False)
    op.create_index(op.f('ix_gen_pop_unem'), 'gen_pop', ['unem'], unique=False)
    op.create_index(op.f('ix_gen_pop_updt'), 'gen_pop', ['updt'], unique=False)
    op.create_index(op.f('ix_gen_pop_urb'), 'gen_pop', ['urb'], unique=False)
    op.create_table('int_land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_int_land_ctry'), 'int_land', ['ctry'], unique=False)
    op.create_index(op.f('ix_int_land_lat'), 'int_land', ['lat'], unique=False)
    op.create_index(op.f('ix_int_land_lon'), 'int_land', ['lon'], unique=False)
    op.create_index(op.f('ix_int_land_name'), 'int_land', ['name'], unique=False)
    op.create_table('mob_br',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mnth', sa.String(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('dls', sa.Float(), nullable=True),
    sa.Column('ups', sa.Float(), nullable=True),
    sa.Column('ltcy', sa.Float(), nullable=True),
    sa.Column('jitt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mob_br_ctry'), 'mob_br', ['ctry'], unique=False)
    op.create_index(op.f('ix_mob_br_dls'), 'mob_br', ['dls'], unique=False)
    op.create_index(op.f('ix_mob_br_jitt'), 'mob_br', ['jitt'], unique=False)
    op.create_index(op.f('ix_mob_br_ltcy'), 'mob_br', ['ltcy'], unique=False)
    op.create_index(op.f('ix_mob_br_mnth'), 'mob_br', ['mnth'], unique=False)
    op.create_index(op.f('ix_mob_br_ups'), 'mob_br', ['ups'], unique=False)
    op.create_table('pop_dens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updt', sa.String(), nullable=True),
    sa.Column('pop_yr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pop_dens_pop_yr'), 'pop_dens', ['pop_yr'], unique=False)
    op.create_index(op.f('ix_pop_dens_updt'), 'pop_dens', ['updt'], unique=False)
    op.create_table('root_srv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('loc', sa.String(), nullable=True),
    sa.Column('oper', sa.String(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('inst', sa.String(), nullable=True),
    sa.Column('rssac', sa.String(), nullable=True),
    sa.Column('con', sa.String(), nullable=True),
    sa.Column('peer', sa.String(), nullable=True),
    sa.Column('id_root', sa.String(), nullable=True),
    sa.Column('id_nc', sa.String(), nullable=True),
    sa.Column('sub', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_srv_asn'), 'root_srv', ['asn'], unique=False)
    op.create_index(op.f('ix_root_srv_con'), 'root_srv', ['con'], unique=False)
    op.create_index(op.f('ix_root_srv_ctry'), 'root_srv', ['ctry'], unique=False)
    op.create_index(op.f('ix_root_srv_id_nc'), 'root_srv', ['id_nc'], unique=False)
    op.create_index(op.f('ix_root_srv_id_root'), 'root_srv', ['id_root'], unique=False)
    op.create_index(op.f('ix_root_srv_inst'), 'root_srv', ['inst'], unique=False)
    op.create_index(op.f('ix_root_srv_ipv4'), 'root_srv', ['ipv4'], unique=False)
    op.create_index(op.f('ix_root_srv_ipv6'), 'root_srv', ['ipv6'], unique=False)
    op.create_index(op.f('ix_root_srv_loc'), 'root_srv', ['loc'], unique=False)
    op.create_index(op.f('ix_root_srv_name'), 'root_srv', ['name'], unique=False)
    op.create_index(op.f('ix_root_srv_oper'), 'root_srv', ['oper'], unique=False)
    op.create_index(op.f('ix_root_srv_peer'), 'root_srv', ['peer'], unique=False)
    op.create_index(op.f('ix_root_srv_rssac'), 'root_srv', ['rssac'], unique=False)
    op.create_index(op.f('ix_root_srv_sub'), 'root_srv', ['sub'], unique=False)
    op.create_index(op.f('ix_root_srv_type_'), 'root_srv', ['type_'], unique=False)
    op.create_table('src_updt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=True),
    sa.Column('updt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_src_updt_src'), 'src_updt', ['src'], unique=False)
    op.create_index(op.f('ix_src_updt_updt'), 'src_updt', ['updt'], unique=False)
    op.create_table('tld',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctry_', sa.String(), nullable=True),
    sa.Column('cctld', sa.String(), nullable=True),
    sa.Column('ad_con', sa.String(), nullable=True),
    sa.Column('tch_con', sa.String(), nullable=True),
    sa.Column('nm_svr', sa.String(), nullable=True),
    sa.Column('reg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tld_ad_con'), 'tld', ['ad_con'], unique=False)
    op.create_index(op.f('ix_tld_cctld'), 'tld', ['cctld'], unique=False)
    op.create_index(op.f('ix_tld_ctry_'), 'tld', ['ctry_'], unique=False)
    op.create_index(op.f('ix_tld_nm_svr'), 'tld', ['nm_svr'], unique=False)
    op.create_index(op.f('ix_tld_reg'), 'tld', ['reg'], unique=False)
    op.create_index(op.f('ix_tld_tch_con'), 'tld', ['tch_con'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tld_tch_con'), table_name='tld')
    op.drop_index(op.f('ix_tld_reg'), table_name='tld')
    op.drop_index(op.f('ix_tld_nm_svr'), table_name='tld')
    op.drop_index(op.f('ix_tld_ctry_'), table_name='tld')
    op.drop_index(op.f('ix_tld_cctld'), table_name='tld')
    op.drop_index(op.f('ix_tld_ad_con'), table_name='tld')
    op.drop_table('tld')
    op.drop_index(op.f('ix_src_updt_updt'), table_name='src_updt')
    op.drop_index(op.f('ix_src_updt_src'), table_name='src_updt')
    op.drop_table('src_updt')
    op.drop_index(op.f('ix_root_srv_type_'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_sub'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_rssac'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_peer'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_oper'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_name'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_loc'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_ipv6'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_ipv4'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_inst'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_id_root'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_id_nc'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_ctry'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_con'), table_name='root_srv')
    op.drop_index(op.f('ix_root_srv_asn'), table_name='root_srv')
    op.drop_table('root_srv')
    op.drop_index(op.f('ix_pop_dens_updt'), table_name='pop_dens')
    op.drop_index(op.f('ix_pop_dens_pop_yr'), table_name='pop_dens')
    op.drop_table('pop_dens')
    op.drop_index(op.f('ix_mob_br_ups'), table_name='mob_br')
    op.drop_index(op.f('ix_mob_br_mnth'), table_name='mob_br')
    op.drop_index(op.f('ix_mob_br_ltcy'), table_name='mob_br')
    op.drop_index(op.f('ix_mob_br_jitt'), table_name='mob_br')
    op.drop_index(op.f('ix_mob_br_dls'), table_name='mob_br')
    op.drop_index(op.f('ix_mob_br_ctry'), table_name='mob_br')
    op.drop_table('mob_br')
    op.drop_index(op.f('ix_int_land_name'), table_name='int_land')
    op.drop_index(op.f('ix_int_land_lon'), table_name='int_land')
    op.drop_index(op.f('ix_int_land_lat'), table_name='int_land')
    op.drop_index(op.f('ix_int_land_ctry'), table_name='int_land')
    op.drop_table('int_land')
    op.drop_index(op.f('ix_gen_pop_urb'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_updt'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_unem'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_pov'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_pop'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_occ'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_lit'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_lang'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_land'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_lab'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_gen'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_elec'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_cur'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_ctry_'), table_name='gen_pop')
    op.drop_index(op.f('ix_gen_pop_area'), table_name='gen_pop')
    op.drop_table('gen_pop')
    op.drop_index(op.f('ix_fixed_br_ups'), table_name='fixed_br')
    op.drop_index(op.f('ix_fixed_br_mnth'), table_name='fixed_br')
    op.drop_index(op.f('ix_fixed_br_ltcy'), table_name='fixed_br')
    op.drop_index(op.f('ix_fixed_br_jitt'), table_name='fixed_br')
    op.drop_index(op.f('ix_fixed_br_dls'), table_name='fixed_br')
    op.drop_index(op.f('ix_fixed_br_ctry'), table_name='fixed_br')
    op.drop_table('fixed_br')
    op.drop_index(op.f('ix_car_land_name'), table_name='car_land')
    op.drop_index(op.f('ix_car_land_lon'), table_name='car_land')
    op.drop_index(op.f('ix_car_land_lat'), table_name='car_land')
    op.drop_index(op.f('ix_car_land_ctry'), table_name='car_land')
    op.drop_table('car_land')
    op.drop_index(op.f('ix_USD_year'), table_name='USD')
    op.drop_index(op.f('ix_USD_mob'), table_name='USD')
    op.drop_index(op.f('ix_USD_low'), table_name='USD')
    op.drop_index(op.f('ix_USD_high'), table_name='USD')
    op.drop_index(op.f('ix_USD_fix'), table_name='USD')
    op.drop_index(op.f('ix_USD_ctry'), table_name='USD')
    op.drop_table('USD')
    op.drop_index(op.f('ix_PPP_year'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_mob'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_low'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_high'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_fix'), table_name='PPP')
    op.drop_index(op.f('ix_PPP_ctry'), table_name='PPP')
    op.drop_table('PPP')
    op.drop_index(op.f('ix_ICT_per_yrs'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_vg'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_vc'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_tt'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_tc'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_sr'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_ms'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_lc'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_ky'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_kn'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_jm'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_ht'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_gy'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_gd'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_dm'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_bz'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_bs'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_bm'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_bb'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_ai'), table_name='ICT_per')
    op.drop_index(op.f('ix_ICT_per_ag'), table_name='ICT_per')
    op.drop_table('ICT_per')
    op.drop_index(op.f('ix_ICT_mob_yrs'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_vg'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_vc'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_tt'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_tc'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_sr'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_ms'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_lc'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_ky'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_kn'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_jm'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_ht'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_gy'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_gd'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_dm'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_bz'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_bs'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_bm'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_bb'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_ai'), table_name='ICT_mob')
    op.drop_index(op.f('ix_ICT_mob_ag'), table_name='ICT_mob')
    op.drop_table('ICT_mob')
    op.drop_index(op.f('ix_ICT_fix_yrs'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_vg'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_vc'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_tt'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_tc'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_sr'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_ms'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_lc'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_ky'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_kn'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_jm'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_ht'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_gy'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_gd'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_dm'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_bz'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_bs'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_bm'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_bb'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_ai'), table_name='ICT_fix')
    op.drop_index(op.f('ix_ICT_fix_ag'), table_name='ICT_fix')
    op.drop_table('ICT_fix')
    op.drop_index(op.f('ix_ICT_bw_yrs'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_vg'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_vc'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_tt'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_tc'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_sr'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_ms'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_lc'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_ky'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_kn'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_jm'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_ht'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_gy'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_gd'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_dm'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_bz'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_bs'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_bm'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_bb'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_ai'), table_name='ICT_bw')
    op.drop_index(op.f('ix_ICT_bw_ag'), table_name='ICT_bw')
    op.drop_table('ICT_bw')
    op.drop_index(op.f('ix_GNI_year'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_mob'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_low'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_high'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_fix'), table_name='GNI')
    op.drop_index(op.f('ix_GNI_ctry'), table_name='GNI')
    op.drop_table('GNI')
    # ### end Alembic commands ###
